package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EgispRssAppkey generated by hbm2java
 */
@Entity
@Table(name = "EGISP_RSS_APPKEY")
public class AppkeyEntity extends IdEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String appKey;
	private Date createTime;
	private String remark;
	private String userId;

	public AppkeyEntity() {
	}


	public AppkeyEntity(String id, String appKey, Date createTime, String remark, String userId) {
		this.id = id;
		this.appKey = appKey;
		this.createTime = createTime;
		this.remark = remark;
		this.userId = userId;
	}

	@Column(name = "app_key", length = 32)
	public String getAppKey() {
		return this.appKey;
	}

	public void setAppKey(String appKey) {
		this.appKey = appKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "remark", length = 256)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "user_id", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
