package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * HistoryOrder generated by hbm2java
 */
@Entity
@Table(name = "HISTORY_ORDER")
public class HistoryOrderEntity implements java.io.Serializable {

	private String id;
	private String number;
	private String batch;
	private String admincode;
	private String province;
	private String city;
	private String county;
	private String address;
	private Byte orderStatusId;
	private Date statusUpdateTime;
	private Date importTime;
	private Byte deleteFlag;
	private String createUserId;
	private String enterpriseId;
	private String departmentId;
	private String customerName;
	private String customerPhone;
	private String productName;
	private Integer productCount;
	private BigDecimal productPrice;
	private String supplier;
	private Date deliveryTime;
	private Byte fendanStatusId;
	private BigDecimal smx;
	private BigDecimal smy;
	private String areaId;
	private String fendanUserId;
	private Date fendanTime;

	public HistoryOrderEntity() {
	}

	public HistoryOrderEntity(String id, String number, String batch, String admincode, String province, String city, String county, String address, Byte orderStatusId,
			Date statusUpdateTime, Date importTime, Byte deleteFlag, String createUserId, String enterpriseId, String departmentId, String customerName,
			String customerPhone, String productName, Integer productCount, BigDecimal productPrice, String supplier, Date deliveryTime, Byte fendanStatusId,
			BigDecimal smx, BigDecimal smy, String areaId, String fendanUserId, Date fendanTime) {
		this.id = id;
		this.number = number;
		this.batch = batch;
		this.admincode = admincode;
		this.province = province;
		this.city = city;
		this.county = county;
		this.address = address;
		this.orderStatusId = orderStatusId;
		this.statusUpdateTime = statusUpdateTime;
		this.importTime = importTime;
		this.deleteFlag = deleteFlag;
		this.createUserId = createUserId;
		this.enterpriseId = enterpriseId;
		this.departmentId = departmentId;
		this.customerName = customerName;
		this.customerPhone = customerPhone;
		this.productName = productName;
		this.productCount = productCount;
		this.productPrice = productPrice;
		this.supplier = supplier;
		this.deliveryTime = deliveryTime;
		this.fendanStatusId = fendanStatusId;
		this.smx = smx;
		this.smy = smy;
		this.areaId = areaId;
		this.fendanUserId = fendanUserId;
		this.fendanTime = fendanTime;
	}

	@Id
	@GenericGenerator(name = "orderIdGenerator", strategy = "assigned")
    @GeneratedValue(generator = "orderIdGenerator")
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}
	
	@Column(name = "number", length = 16)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "batch", length = 16)
	public String getBatch() {
		return this.batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}
	
	@Column(name = "admincode", length = 16)
	public String getAdmincode() {
		return admincode;
	}

	public void setAdmincode(String admincode) {
		this.admincode = admincode;
	}

	@Column(name = "province", length = 8)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "city", length = 32)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "county", length = 32)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "address", length = 32)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "order_status_id")
	public Byte getOrderStatusId() {
		return this.orderStatusId;
	}

	public void setOrderStatusId(Byte orderStatusId) {
		this.orderStatusId = orderStatusId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "status_update_time", length = 19)
	public Date getStatusUpdateTime() {
		return this.statusUpdateTime;
	}

	public void setStatusUpdateTime(Date statusUpdateTime) {
		this.statusUpdateTime = statusUpdateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "import_time", length = 19)
	public Date getImportTime() {
		return this.importTime;
	}

	public void setImportTime(Date importTime) {
		this.importTime = importTime;
	}

	@Column(name = "delete_flag")
	public Byte getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Byte deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Column(name = "create_user_id", length = 32)
	public String getCreateUserId() {
		return this.createUserId;
	}

	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	@Column(name = "enterprise_id", length = 32)
	public String getEnterpriseId() {
		return this.enterpriseId;
	}

	public void setEnterpriseId(String enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	@Column(name = "department_id", length = 32)
	public String getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "customer_name", length = 8)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "customer_phone", length = 11)
	public String getCustomerPhone() {
		return this.customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	@Column(name = "product_name", length = 16)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "product_count")
	public Integer getProductCount() {
		return this.productCount;
	}

	public void setProductCount(Integer productCount) {
		this.productCount = productCount;
	}

	@Column(name = "product_price", precision = 8)
	public BigDecimal getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(BigDecimal productPrice) {
		this.productPrice = productPrice;
	}

	@Column(name = "supplier", length = 16)
	public String getSupplier() {
		return this.supplier;
	}

	public void setSupplier(String supplier) {
		this.supplier = supplier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delivery_time", length = 19)
	public Date getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	@Column(name = "fendan_status_id")
	public Byte getFendanStatusId() {
		return this.fendanStatusId;
	}

	public void setFendanStatusId(Byte fendanStatusId) {
		this.fendanStatusId = fendanStatusId;
	}

	@Column(name = "smx", precision = 38, scale = 16)
	public BigDecimal getSmx() {
		return this.smx;
	}

	public void setSmx(BigDecimal smx) {
		this.smx = smx;
	}

	@Column(name = "smy", precision = 38, scale = 16)
	public BigDecimal getSmy() {
		return this.smy;
	}

	public void setSmy(BigDecimal smy) {
		this.smy = smy;
	}

	@Column(name = "area_id", length = 32)
	public String getAreaId() {
		return this.areaId;
	}

	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}

	@Column(name = "fendan_user_id", length = 32)
	public String getFendanUserId() {
		return this.fendanUserId;
	}

	public void setFendanUserId(String fendanUserId) {
		this.fendanUserId = fendanUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fendan_time", length = 19)
	public Date getFendanTime() {
		return this.fendanTime;
	}

	public void setFendanTime(Date fendanTime) {
		this.fendanTime = fendanTime;
	}

}
