package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InfoRole generated by hbm2java
 */
@Entity
@Table(name = "INFO_ROLE")
public class InfoRoleEntity extends IdEntity implements java.io.Serializable {

	private String name;
	private String remark;
	private byte level;
	private String eid;
	private String createUserid;
	private Date operDate;

	public InfoRoleEntity() {
	}

	public InfoRoleEntity(String id, String name, byte level, String eid, String createUserid, Date operDate) {
		this.id = id;
		this.name = name;
		this.level = level;
		this.eid = eid;
		this.createUserid = createUserid;
		this.operDate = operDate;
	}

	public InfoRoleEntity(String id, String name, String remark, byte level, String eid, String createUserid, Date operDate) {
		this.id = id;
		this.name = name;
		this.remark = remark;
		this.level = level;
		this.eid = eid;
		this.createUserid = createUserid;
		this.operDate = operDate;
	}

	@Column(name = "NAME", nullable = false, length = 16)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "REMARK", length = 128)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "LEVEL", nullable = false)
	public byte getLevel() {
		return this.level;
	}

	public void setLevel(byte level) {
		this.level = level;
	}

	@Column(name = "EID", nullable = false, length = 32)
	public String getEid() {
		return this.eid;
	}

	public void setEid(String eid) {
		this.eid = eid;
	}

	@Column(name = "CREATE_USERID", nullable = false, length = 32)
	public String getCreateUserid() {
		return this.createUserid;
	}

	public void setCreateUserid(String createUserid) {
		this.createUserid = createUserid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OPER_DATE", nullable = false, length = 19)
	public Date getOperDate() {
		return this.operDate;
	}

	public void setOperDate(Date operDate) {
		this.operDate = operDate;
	}

}
