package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * InfoRoleFunction generated by hbm2java
 */
@Entity
@Table(name = "INFO_ROLE_FUNCTION")
public class InfoRoleFunctionEntity extends IdEntity implements java.io.Serializable {

	private String roleId;
	private String funId;

	public InfoRoleFunctionEntity() {
	}

	public InfoRoleFunctionEntity(String id, String roleId, String funId) {
		this.id = id;
		this.roleId = roleId;
		this.funId = funId;
	}

	@Column(name = "ROLE_ID", length = 32)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "FUN_ID", length = 32)
	public String getFunId() {
		return this.funId;
	}

	public void setFunId(String funId) {
		this.funId = funId;
	}

}
