package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * BizMapPointCar generated by hbm2java
 */
@Entity
@Table(name = "BIZ_MAP_POINT_CAR", catalog = "egisp_dev")
public class MapPointCarEntity extends IdEntity implements java.io.Serializable {

	private String pointId;
	private String carId;

	public MapPointCarEntity() {
	}

	public MapPointCarEntity(String id) {
		this.id = id;
	}

	public MapPointCarEntity(String id, String pointId, String carId) {
		this.id = id;
		this.pointId = pointId;
		this.carId = carId;
	}


	@Column(name = "point_id", length = 32)
	public String getPointId() {
		return this.pointId;
	}

	public void setPointId(String pointId) {
		this.pointId = pointId;
	}

	@Column(name = "car_id", length = 32)
	public String getCarId() {
		return this.carId;
	}

	public void setCarId(String carId) {
		this.carId = carId;
	}

}
