package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * OrderFendan generated by hbm2java
 */
@Entity
@Table(name = "ORDER_FENDAN")
public class OrderFendanEntity implements java.io.Serializable {

	private String id;
	private Byte fendanStatusId;
	private BigDecimal smx;
	private BigDecimal smy;
	private String areaId;
	private String userId;
	private Date fendanTime;
	private String department_id;

	public OrderFendanEntity() {
	}

	public OrderFendanEntity(String id, Byte fendanStatusId, BigDecimal smx, BigDecimal smy, String areaId, String userId, Date fendanTime) {
		this.id = id;
		this.fendanStatusId = fendanStatusId;
		this.smx = smx;
		this.smy = smy;
		this.areaId = areaId;
		this.userId = userId;
		this.fendanTime = fendanTime;
	}
	
	@Id
	@GenericGenerator(name = "orderIdGenerator", strategy = "assigned")
    @GeneratedValue(generator = "orderIdGenerator")
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "fendan_status_id")
	public Byte getFendanStatusId() {
		return this.fendanStatusId;
	}

	public void setFendanStatusId(Byte fendanStatusId) {
		this.fendanStatusId = fendanStatusId;
	}

	@Column(name = "smx", precision = 38, scale = 16)
	public BigDecimal getSmx() {
		return this.smx;
	}

	public void setSmx(BigDecimal smx) {
		this.smx = smx;
	}

	@Column(name = "smy", precision = 38, scale = 16)
	public BigDecimal getSmy() {
		return this.smy;
	}

	public void setSmy(BigDecimal smy) {
		this.smy = smy;
	}

	@Column(name = "area_id", length = 32)
	public String getAreaId() {
		return this.areaId;
	}

	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}

	@Column(name = "user_id", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fendan_time", length = 19)
	public Date getFendanTime() {
		return this.fendanTime;
	}

	public void setFendanTime(Date fendanTime) {
		this.fendanTime = fendanTime;
	}

	@Column(name="department_id",length=32)
	public String getDepartment_id() {
		return department_id;
	}

	public void setDepartment_id(String departmentId) {
		department_id = departmentId;
	}

}
