package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderBase generated by hbm2java
 */
@Entity
@Table(name = "ORDER_BASE")
public class OrderBaseEntity extends IdEntity implements java.io.Serializable {

	private String number;
	private String batch;
	private String admincode;
	private String province;
	private String city;
	private String county;
	private String address;
	private Byte orderStatusId;
	private Date statusUpdateTime;
	private Date importTime;
	private Byte deleteFlag;
	private String userId;
	private String enterpriseId;
	private String departmentId;

	public OrderBaseEntity() {
	}

	public OrderBaseEntity(String id, String number, String batch, String admincode, String province, String city, String county, String address, Byte orderStatusId,
			Date statusUpdateTime, Date importTime, Byte deleteFlag, String userId, String enterpriseId, String departmentId) {
		this.id = id;
		this.number = number;
		this.batch = batch;
		this.admincode = admincode;
		this.province = province;
		this.city = city;
		this.county = county;
		this.address = address;
		this.orderStatusId = orderStatusId;
		this.statusUpdateTime = statusUpdateTime;
		this.importTime = importTime;
		this.deleteFlag = deleteFlag;
		this.userId = userId;
		this.enterpriseId = enterpriseId;
		this.departmentId = departmentId;
	}

	@Column(name = "number", length = 32)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}
	
	@Column(name = "admincode", length = 16)
	public String getAdmincode() {
		return admincode;
	}

	public void setAdmincode(String admincode) {
		this.admincode = admincode;
	}

	@Column(name = "batch", length = 16)
	public String getBatch() {
		return this.batch;
	}

	public void setBatch(String batch) {
		this.batch = batch;
	}

	@Column(name = "province", length = 8)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "city", length = 32)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "county", length = 32)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "address", length = 32)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "order_status_id")
	public Byte getOrderStatusId() {
		return this.orderStatusId;
	}

	public void setOrderStatusId(Byte orderStatusId) {
		this.orderStatusId = orderStatusId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "status_update_time", length = 19)
	public Date getStatusUpdateTime() {
		return this.statusUpdateTime;
	}

	public void setStatusUpdateTime(Date statusUpdateTime) {
		this.statusUpdateTime = statusUpdateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "import_time", length = 19)
	public Date getImportTime() {
		return this.importTime;
	}

	public void setImportTime(Date importTime) {
		this.importTime = importTime;
	}

	@Column(name = "delete_flag")
	public Byte getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Byte deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Column(name = "user_id", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "enterprise_id", length = 32)
	public String getEnterpriseId() {
		return this.enterpriseId;
	}

	public void setEnterpriseId(String enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	@Column(name = "department_id", length = 32)
	public String getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

}
