package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;


/**
 * EgispRssPrivlege generated by hbm2java
 */
@Entity
@Table(name = "EGISP_RSS_PRIVLEGE")
public class PrivlegeEntity extends IdEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String name;
	private String code; 
	private PrivilegeStatusEntity status;
	private int level = 1;
	private String remarks;
	private String url;
	private PrivlegeEntity parent;
	private Set<PrivlegeEntity> childs = new HashSet<PrivlegeEntity>();
	private Set<RoleEntity> roles = new HashSet<RoleEntity>();

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PrivlegeEntity other = (PrivlegeEntity) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	
	@Column(name="name",length=50)
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
	@Column(name="code",length=50)
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}


	@Column(name="level")
	public int getLevel() {
		return level;
	}

	public void setLevel(int level) {
		this.level = level;
	}
	@Column(name="remark",length=500)
	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	@Column(name="url",length=100)
	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
	@ManyToOne(cascade=CascadeType.REFRESH,fetch=FetchType.EAGER)
	@JoinColumn(name="pid")
	public PrivlegeEntity getParent() {
		return parent;
	}

	public void setParent(PrivlegeEntity parent) {
		this.parent = parent;
	}
	@OneToMany(cascade=CascadeType.ALL,mappedBy="parent")
	public Set<PrivlegeEntity> getChilds() {
		return childs;
	}

	public void setChilds(Set<PrivlegeEntity> childs) {
		this.childs = childs;
	}
	@ManyToMany(cascade={CascadeType.REFRESH},mappedBy="privileges")
	public Set<RoleEntity> getRoles() {
		return roles;
	}

	public void setRoles(Set<RoleEntity> roles) {
		this.roles = roles;
	}
	@ManyToOne(cascade={CascadeType.REFRESH})
	@JoinColumn(name="status_id",nullable=false)
	public PrivilegeStatusEntity getStatus() {
		return status;
	}

	public void setStatus(PrivilegeStatusEntity status) {
		this.status = status;
	}
	

}
