package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * EgispRssServiceModule generated by hbm2java
 */
@Entity
@Table(name = "EGISP_RSS_SERVICE_MODULE")
public class ServiceModuleEntity extends IdEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String name;
	private BigDecimal price;
	private String url;
	private String refUrl;
	private Integer useLimit=10000;
	private String remark;
	private ModuleStatusEntity statusId;
	private Date addTime = new Date();
	private Date updateTime;
	private ServiceModuleEntity parent;
	private String code;
	private String iconUrl;

	public ServiceModuleEntity() {
	}

	public ServiceModuleEntity(String name, BigDecimal price, String url, String refUrl, Integer useLimit, String remark, ModuleStatusEntity statusId, Date addTime,
			Date updateTime, ServiceModuleEntity pid, String code, String iconUrl) {
		super();
		this.name = name;
		this.price = price;
		this.url = url;
		this.refUrl = refUrl;
		this.useLimit = useLimit;
		this.remark = remark;
		this.statusId = statusId;
		this.addTime = addTime;
		this.updateTime = updateTime;
		this.parent = pid;
		this.code = code;
		this.iconUrl = iconUrl;
	}

	@Column(name = "name", length = 16)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", precision = 8)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "url", length = 256)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "ref_url", length = 256)
	public String getRefUrl() {
		return this.refUrl;
	}

	public void setRefUrl(String refUrl) {
		this.refUrl = refUrl;
	}

	@Column(name = "use_limit")
	public Integer getUseLimit() {
		return this.useLimit;
	}

	public void setUseLimit(Integer useLimit) {
		this.useLimit = useLimit;
	}

	@Column(name = "remark", length = 256)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * 状态：1，公开发布；2，Beta测试；3，撤销；4，其它
	 */
	@ManyToOne(cascade={CascadeType.REFRESH})
	@JoinColumn(name="status_id",nullable=false)
	public ModuleStatusEntity getStatusId() {
		return this.statusId;
	}

	public void setStatusId(ModuleStatusEntity statusId) {
		this.statusId = statusId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "add_time", length = 19)
	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@ManyToOne(cascade={CascadeType.REFRESH,CascadeType.MERGE})
	@JoinColumn(name="pid",nullable=true)
	public ServiceModuleEntity getParent() {
		return this.parent;
	}

	public void setParent(ServiceModuleEntity pid) {
		this.parent = pid;
	}

	@Column(name = "code", length = 16)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "icon_url", length = 64)
	public String getIconUrl() {
		return iconUrl;
	}

	public void setIconUrl(String iconUrl) {
		this.iconUrl = iconUrl;
	}
	
	
	private List<ServiceModuleEntity> serviceModules = new ArrayList<ServiceModuleEntity>();

	@OneToMany(cascade=CascadeType.ALL,mappedBy="parent")
	public List<ServiceModuleEntity> getServiceModules(){
		return serviceModules;
	}
	
	public void setServiceModules(List<ServiceModuleEntity> sets) {
		this.serviceModules = sets;
	}

	public void add(ServiceModuleEntity sme){
		sme.setParent(this);
		serviceModules.add(sme);
	}
	
	
	/**
	 * 1:基础产品，2：物流产品
	 */
	private String type = "1";
	
	@Column(name="mtype",length=4)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
}
