package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EgispRssOrderItems generated by hbm2java
 */
@Entity
@Table(name = "EGISP_RSS_ORDER_ITEMS", catalog = "egisp_dev")
public class OrderItemsEntity  implements java.io.Serializable {

	private String id;
	private String orderId;
	private String moduleId;
	private BigDecimal consultPrice = BigDecimal.ONE;
	private Integer useLimit=0;
	private Date useTime;
	private Date deadline;
	private int item_type = 0;
	private String isLogined = null;

	@Column(name="item_type")
	public int getItem_type() {
		return item_type;
	}


	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 35)
	public String getId() {
		return id;
	}


	public void setId(String id) {
		this.id = id;
	}


	public void setItem_type(int itemType) {
		item_type = itemType;
	}


	public OrderItemsEntity() {
	}


	public OrderItemsEntity(String id, String orderId, String moduleId, BigDecimal consultPrice, Integer useLimit, Date useTime, Date deadline) {
		this.id = id;
		this.orderId = orderId;
		this.moduleId = moduleId;
		this.consultPrice = consultPrice;
		this.useLimit = useLimit;
		this.useTime = useTime;
		this.deadline = deadline;
	}

	@Column(name = "order_id", length = 32)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "module_id", length = 32)
	public String getModuleId() {
		return this.moduleId;
	}

	public void setModuleId(String moduleId) {
		this.moduleId = moduleId;
	}

	@Column(name = "consult_price", precision = 8)
	public BigDecimal getConsultPrice() {
		return this.consultPrice;
	}

	public void setConsultPrice(BigDecimal consultPrice) {
		this.consultPrice = consultPrice;
	}

	@Column(name = "use_limit")
	public Integer getUseLimit() {
		return this.useLimit;
	}

	public void setUseLimit(Integer useLimit) {
		this.useLimit = useLimit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "use_time", length = 19)
	public Date getUseTime() {
		return this.useTime;
	}

	public void setUseTime(Date useTime) {
		this.useTime = useTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deadline", length = 19)
	public Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}


	@Column(name="isLogined",length=1)
	public String getIsLogined() {
		return isLogined;
	}


	public void setIsLogined(String isLogined) {
		this.isLogined = isLogined;
	}
	
	

}
