package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EgispRssOrder generated by hbm2java
 */
@Entity
@Table(name = "EGISP_RSS_ORDER", catalog = "egisp_dev")
public class OrderEntity  implements java.io.Serializable {

	private String id;
	private String userId;
	private String eid;
	private BigDecimal totalSum = BigDecimal.ZERO;
	private BigDecimal consultSum = BigDecimal.ZERO;
	private String auditRemark;
	private Byte statusId;
	private Date submitTime;
	private Date updateTime;
	private String remark;
	private String mainModuleId;
	
	@Column(name="order_type",nullable=false)
	private int orderType = 0;

	
	
	public OrderEntity() {
	}
	
	
	

	public OrderEntity(String id, String userId, String eid, BigDecimal totalSum, BigDecimal consultSum, String auditRemark, Byte statusId, Date submitTime,
			Date updateTime, String remark) {
		this.id = id;
		this.userId = userId;
		this.eid = eid;
		this.totalSum = totalSum;
		this.consultSum = consultSum;
		this.auditRemark = auditRemark;
		this.statusId = statusId;
		this.submitTime = submitTime;
		this.updateTime = updateTime;
		this.remark = remark;
	}

	
	
	
	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 35)
	public String getId() {
		return id;
	}




	public void setId(String id) {
		this.id = id;
	}




	@Column(name="mainModuleId",length=32)
	public String getMainModuleId() {
		return mainModuleId;
	}




	public void setMainModuleId(String mainModuleId) {
		this.mainModuleId = mainModuleId;
	}




	@Column(name = "user_id", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "eid", length = 32)
	public String getEid() {
		return this.eid;
	}

	public void setEid(String eid) {
		this.eid = eid;
	}

	@Column(name = "total_sum", precision = 8)
	public BigDecimal getTotalSum() {
		return this.totalSum;
	}

	public void setTotalSum(BigDecimal totalSum) {
		this.totalSum = totalSum;
	}

	@Column(name = "consult_sum", precision = 8)
	public BigDecimal getConsultSum() {
		return this.consultSum;
	}

	public void setConsultSum(BigDecimal consultSum) {
		this.consultSum = consultSum;
	}

	@Column(name = "audit_remark", length = 256)
	public String getAuditRemark() {
		return this.auditRemark;
	}

	public void setAuditRemark(String auditRemark) {
		this.auditRemark = auditRemark;
	}

	@Column(name = "status_id")
	public Byte getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Byte statusId) {
		this.statusId = statusId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "submit_time", length = 19)
	public Date getSubmitTime() {
		return this.submitTime;
	}

	public void setSubmitTime(Date submitTime) {
		this.submitTime = submitTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "remark", length = 256)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public int getOrderType() {
		return orderType;
	}

	public void setOrderType(int orderType) {
		this.orderType = orderType;
	}

}
