package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RouteTask generated by hbm2java
 */
@Entity
@Table(name = "ROUTE_TASK", catalog = "egisp_dev")
public class RouteTaskEntity extends IdEntity implements java.io.Serializable {

	private Byte planTypeId;
	private String areaId;
	private String areaName;
	private Integer orderCount;
	private Byte taskStatusId;
	private Integer consumeTime;
	private Date planTime;
	private Date deliveryStartTime;
	private Date deliveryEndTime;
	private String resultPath;
	private Date createTime;
	private Byte deleteFlag;
	private UserEntity userId;
	private ComEntity enterpriseId;
	private InfoDeptEntity departmentId;
	private String typePath;
	private String typeAnalysis;
	private String typeTrac;
	private String taskName;
	private int pathCount;

	@Column(name = "plan_type_id")
	public Byte getPlanTypeId() {
		return this.planTypeId;
	}

	public void setPlanTypeId(Byte planTypeId) {
		this.planTypeId = planTypeId;
	}

	@Column(name = "area_id", length = 32)
	public String getAreaId() {
		return this.areaId;
	}

	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}

	@Column(name = "area_name", length = 100)
	public String getAreaName() {
		return areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@Column(name = "order_count")
	public Integer getOrderCount() {
		return this.orderCount;
	}

	public void setOrderCount(Integer orderCount) {
		this.orderCount = orderCount;
	}

	@Column(name = "task_status_id")
	public Byte getTaskStatusId() {
		return this.taskStatusId;
	}

	public void setTaskStatusId(Byte taskStatusId) {
		this.taskStatusId = taskStatusId;
	}

	@Column(name = "consume_time")
	public Integer getConsumeTime() {
		return this.consumeTime;
	}

	public void setConsumeTime(Integer consumeTime) {
		this.consumeTime = consumeTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "plan_time", length = 19)
	public Date getPlanTime() {
		return this.planTime;
	}

	public void setPlanTime(Date planTime) {
		this.planTime = planTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delivery_start_time", length = 19)
	public Date getDeliveryStartTime() {
		return this.deliveryStartTime;
	}

	public void setDeliveryStartTime(Date deliveryStartTime) {
		this.deliveryStartTime = deliveryStartTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delivery_end_time", length = 19)
	public Date getDeliveryEndTime() {
		return this.deliveryEndTime;
	}

	public void setDeliveryEndTime(Date deliveryEndTime) {
		this.deliveryEndTime = deliveryEndTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "delete_flag")
	public Byte getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Byte deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@ManyToOne
	@JoinColumn(name = "user_id", columnDefinition = "varchar(32)", nullable = false)
	public UserEntity getUserId() {
		return userId;
	}

	public void setUserId(UserEntity userId) {
		this.userId = userId;
	}

	@ManyToOne
	@JoinColumn(name = "enterprise_id", columnDefinition = "varchar(32)", nullable = false)
	public ComEntity getEnterpriseId() {
		return enterpriseId;
	}

	public void setEnterpriseId(ComEntity enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	@ManyToOne
	@JoinColumn(name = "department_id", columnDefinition = "varchar(32)", nullable = false)
	public InfoDeptEntity getDepartmentId() {
		return departmentId;
	}

	public void setDepartmentId(InfoDeptEntity departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "result_path", length = 300)
	public String getResultPath() {
		return resultPath;
	}

	public void setResultPath(String resultPath) {
		this.resultPath = resultPath;
	}

	@Column(name = "type_path", length = 2)
	public String getTypePath() {
		return typePath;
	}

	public void setTypePath(String typePath) {
		this.typePath = typePath;
	}

	@Column(name = "type_analysis", length = 2)
	public String getTypeAnalysis() {
		return typeAnalysis;
	}

	public void setTypeAnalysis(String typeAnalysis) {
		this.typeAnalysis = typeAnalysis;
	}

	@Column(name = "type_trac", length = 2)
	public String getTypeTrac() {
		return typeTrac;
	}

	public void setTypeTrac(String typeTrac) {
		this.typeTrac = typeTrac;
	}

	@Column(name = "task_name", length = 100)
	public String getTaskName() {
		return taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	@Column(name = "path_count", length = 100)
	public int getPathCount() {
		return pathCount;
	}

	public void setPathCount(int pathCount) {
		this.pathCount = pathCount;
	}

}
