package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * EnterpriseUserRoleMap generated by hbm2java
 */
@Entity
@Table(name = "ENTERPRISE_USER_ROLE_MAP", catalog = "egisp_dev")
public class UserRoleMapEntity extends IdEntity implements java.io.Serializable {

	private String userId;
	private String roleId;

	public UserRoleMapEntity() {
	}

	public UserRoleMapEntity(String id, String userId, String roleId) {
		this.id = id;
		this.userId = userId;
		this.roleId = roleId;
	}

	@Column(name = "user_id", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "role_id", length = 32)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

}
