package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * BizPoint generated by hbm2java
 */
@Entity
@Table(name = "BIZ_POINT")
public class PointEntity  extends IdEntity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String name;
	private BigDecimal smx;
	private BigDecimal smy;
	private String address;
	private String dutyName;
	private String dutyPhone;
	private String areaId;
	private Date createTime;
	private Date updateTime;
	private Byte deleteFlag;
	private String userId;
	private String enterpriseId;
	private String departmentId;
	private int status = 0;//0 可用 ； 1 不可用 ； 2 处理中
	
	private String netPicPath;
	private String dutyPicPath;
	private String iconStyle;
	
	private String admincode;
	private String province;
	private String city;
	private String county;
	
	
	public PointEntity() {
	}

	public PointEntity(
			String id, 
			String name, BigDecimal smx, BigDecimal smy, String dutyName, String dutyPhone, String areaId, Date createTime, Date updateTime,
			Byte deleteFlag, String userId, String enterpriseId, String departmentId
			//,PointExtcolValEntity pointExtcolValEntity
			,String admincode,String province,String city,String county
			) {
		this.id = id;
		this.name = name;
		this.smx = smx;
		this.smy = smy;
		this.dutyName = dutyName;
		this.dutyPhone = dutyPhone;
		this.areaId = areaId;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.deleteFlag = deleteFlag;
		this.userId = userId;
		this.enterpriseId = enterpriseId;
		this.departmentId = departmentId;
		//this.pointExtcolValEntity=pointExtcolValEntity;
		this.admincode=admincode;
		this.province=province;
		this.city=city;
		this.county=county;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "smx", precision = 38, scale = 16)
	public BigDecimal getSmx() {
		return this.smx;
	}

	public void setSmx(BigDecimal smx) {
		this.smx = smx;
	}

	@Column(name = "smy", precision = 38, scale = 16)
	public BigDecimal getSmy() {
		return this.smy;
	}

	public void setSmy(BigDecimal smy) {
		this.smy = smy;
	}

	@Column(name = "duty_name", length = 8)
	public String getDutyName() {
		return this.dutyName;
	}

	public void setDutyName(String dutyName) {
		this.dutyName = dutyName;
	}

	@Column(name = "duty_phone", length = 30)
	public String getDutyPhone() {
		return this.dutyPhone;
	}

	public void setDutyPhone(String dutyPhone) {
		this.dutyPhone = dutyPhone;
	}

	@Column(name = "area_id", length = 32)
	public String getAreaId() {
		return this.areaId;
	}

	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "delete_flag")
	public Byte getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Byte deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	@Column(name = "user_id", length = 32)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "enterprise_id", length = 32)
	public String getEnterpriseId() {
		return this.enterpriseId;
	}

	public void setEnterpriseId(String enterpriseId) {
		this.enterpriseId = enterpriseId;
	}

	@Column(name = "department_id", length = 32)
	public String getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(String departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "address", length = 60)
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name="status")
	public int getStatus() {
		return status;
	}

	@Column(name="net_pic_path",length=200)
	public String getNetPicPath() {
		return netPicPath;
	}

	public void setNetPicPath(String netPicPath) {
		this.netPicPath = netPicPath;
	}

	@Column(name="duty_pic_path",length=200)
	public String getDutyPicPath() {
		return dutyPicPath;
	}

	public void setDutyPicPath(String dutyPicPath) {
		this.dutyPicPath = dutyPicPath;
	}

	@Column(name="icon_style",length=48)
	public String getIconStyle() {
		return iconStyle;
	}

	public void setIconStyle(String iconStyle) {
		this.iconStyle = iconStyle;
	}
	
	

	
	private PointExtcolValEntity pointExtcolValEntity;
	
	@OneToOne(cascade={CascadeType.REMOVE},fetch=FetchType.LAZY,optional = true,mappedBy = "pointEntity")
//	@JoinColumn(name="excId")
	public PointExtcolValEntity getPointExtcolValEntity() {
		return pointExtcolValEntity;
	}

	public void setPointExtcolValEntity(PointExtcolValEntity pointExtcolValEntity) {
		this.pointExtcolValEntity = pointExtcolValEntity;
	}
	
	
	private PointGroupEntity groupid;
	private PointStyleEntity styleid;
	
	
	@ManyToOne(cascade=CascadeType.MERGE)
	@JoinColumn(name="groupid")
	@NotFound(action=NotFoundAction.IGNORE)
	public PointGroupEntity getGroupid() {
		return groupid;
	}

	public void setGroupid(PointGroupEntity groupid) {
		this.groupid = groupid;
	}

	@ManyToOne(cascade=CascadeType.MERGE)
	@JoinColumn(name="styleid")
	@NotFound(action=NotFoundAction.IGNORE)
	public PointStyleEntity getStyleid() {
		return styleid;
	}

	public void setStyleid(PointStyleEntity styleid) {
		this.styleid = styleid;
	}

	@Column(name="admincode",length=16)
	public String getAdmincode() {
		return admincode;
	}

	public void setAdmincode(String admincode) {
		this.admincode = admincode;
	}
	
	@Column(name="province",length=8)
	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name="city",length=32)
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name="county",length=32)
	public String getCounty() {
		return county;
	}

	public void setCounty(String county) {
		this.county = county;
	}
	
	
	
}
