package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RouteMapTaskCondition generated by hbm2java
 */
@Entity
@Table(name = "ROUTE_MAP_TASK_CONDITION", catalog = "egisp_dev")
public class RouteMapTaskConditionEntity extends IdEntity implements java.io.Serializable {

	private String taskId;
	private String conditionId;

	public RouteMapTaskConditionEntity() {
	}

	public RouteMapTaskConditionEntity(String id, String taskId, String conditionId) {
		this.id = id;
		this.taskId = taskId;
		this.conditionId = conditionId;
	}

	@Column(name = "task_id", length = 32)
	public String getTaskId() {
		return this.taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	@Column(name = "condition_id", length = 32)
	public String getConditionId() {
		return this.conditionId;
	}

	public void setConditionId(String conditionId) {
		this.conditionId = conditionId;
	}

}
