package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RouteMapTaskOrder generated by hbm2java
 */
@Entity
@Table(name = "ROUTE_MAP_TASK_ORDER", catalog = "egisp_dev")
public class RouteMapTaskOrderEntity extends IdEntity implements java.io.Serializable {

	private String taskId;
	private String orderId;

	public RouteMapTaskOrderEntity() {
	}

	public RouteMapTaskOrderEntity(String id, String taskId, String orderId) {
		this.id = id;
		this.taskId = taskId;
		this.orderId = orderId;
	}

	@Column(name = "task_id", length = 32)
	public String getTaskId() {
		return this.taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	@Column(name = "order_id", length = 32)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

}
