package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RouteMapTaskCar generated by hbm2java
 */
@Entity
@Table(name = "ROUTE_MAP_TASK_CAR", catalog = "egisp_dev")
public class RouteMapTaskCarEntity  extends IdEntity implements java.io.Serializable {

	private String taskId;
	private String carId;
	private String carName;

	public RouteMapTaskCarEntity() {
	}

	public RouteMapTaskCarEntity(String id,String taskId, String carId, String carName) {
		super();
		this.id=id;
		this.taskId = taskId;
		this.carId = carId;
		this.carName = carName;
	}

	@Column(name = "task_id", length = 32)
	public String getTaskId() {
		return this.taskId;
	}

	public void setTaskId(String taskId) {
		this.taskId = taskId;
	}

	@Column(name = "car_id", length = 32)
	public String getCarId() {
		return this.carId;
	}

	public void setCarId(String carId) {
		this.carId = carId;
	}
	
	@Column(name = "car_name", length = 32)
	public String getCarName() {
		return carName;
	}

	public void setCarName(String carName) {
		this.carName = carName;
	}

}
