package com.supermap.egispservice.base.entity;

// Generated 2014-9-4 11:41:47 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * OrderExt generated by hbm2java
 */
@Entity
@Table(name = "ORDER_EXT", catalog = "egisp_dev")
public class OrderExtEntity implements java.io.Serializable {

	private String id;
	private String customerName;
	private String customerPhone;
	private String productName;
	private Integer productCount;
	private BigDecimal productPrice;
	private String supplier;
	private Date deliveryTime;

	public OrderExtEntity() {
	}

	public OrderExtEntity(String id, String customerName, String customerPhone, String productName, Integer productCount, BigDecimal productPrice, String supplier,
			Date deliveryTime) {
		this.id = id;
		this.customerName = customerName;
		this.customerPhone = customerPhone;
		this.productName = productName;
		this.productCount = productCount;
		this.productPrice = productPrice;
		this.supplier = supplier;
		this.deliveryTime = deliveryTime;
	}
	
	@Id
	@GenericGenerator(name = "orderIdGenerator", strategy = "assigned")
    @GeneratedValue(generator = "orderIdGenerator")
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "customer_name", length = 8)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "customer_phone", length = 11)
	public String getCustomerPhone() {
		return this.customerPhone;
	}

	public void setCustomerPhone(String customerPhone) {
		this.customerPhone = customerPhone;
	}

	@Column(name = "product_name", length = 16)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "product_count")
	public Integer getProductCount() {
		return this.productCount;
	}

	public void setProductCount(Integer productCount) {
		this.productCount = productCount;
	}

	@Column(name = "product_price", precision = 8)
	public BigDecimal getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(BigDecimal productPrice) {
		this.productPrice = productPrice;
	}

	@Column(name = "supplier", length = 16)
	public String getSupplier() {
		return this.supplier;
	}

	public void setSupplier(String supplier) {
		this.supplier = supplier;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delivery_time", length = 19)
	public Date getDeliveryTime() {
		return this.deliveryTime;
	}

	public void setDeliveryTime(Date deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

}
